# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://conductor.ddavison.io
title: Conductor
email: sircapsalot@gmail.com
description: >
  Conductor is a fluent interface wrapper for the Selenium WebDriver written in Java.
  The framework utilizes the power of CSS, to be an extremely easy and effective framework
  for QA engineers.  Conductor is currently being used by companies such as InboundNow, Major League Gaming (MLG)

excerpt_separator: ""
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: download
    url: https://github.com/ddavison/conductor/archive/master.zip
  - title: github
    url: https://github.com/ddavison/conductor
  - title: maven
    url: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22conductor%22
